name: Build and Deploy SIG App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sigapp:latest .

      # 4. Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sigapp:latest

      # 5. Déploiement sur VM Azure
      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
           # Arrêter et supprimer l'ancien container s'il existe
            docker stop sigapp || true
            docker rm sigapp || true

            # Pull la dernière image
            docker pull ${{ secrets.DOCKER_USERNAME }}/sigapp:latest
          
             # Lancer le container avec le bon mapping de ports
            docker run -d -p 5000:80 --name sigapp ${{ secrets.DOCKER_USERNAME }}/sigapp:latest
            